<a href="https://colab.research.google.com/github/036takashima/python_ds/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# lec7

In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]
my_array1 = np.array(my_list1)

In [3]:
my_array1

array([1, 2, 3, 4])

In [4]:
my_list2 = [11,22,33,44]
my_lists = [my_list1, my_list2]

In [5]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [6]:
my_array2 = np.array(my_lists)

In [7]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [8]:
my_array2.shape

(2, 4)

In [9]:
my_array2.dtype

dtype('int64')

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
my_zeros = np.zeros(5)

In [12]:
dtype(my_zeros)

NameError: ignored

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty((3,4))

array([[4.66783102e-310, 0.00000000e+000, 7.92975362e-321,
        4.66783111e-310],
       [6.91440575e-310, 4.66783111e-310, 6.91440575e-310,
        6.91440575e-310],
       [0.00000000e+000, 1.48219694e-323, 6.36598737e-314,
        5.43472210e-323]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# lec8

In [19]:
import numpy as np

In [20]:
5/2

2.5

In [21]:
5//2

2

In [24]:
arr1 = np.array([[1,2,3,4],
                 [8,9,10,11]])

In [25]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [26]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [27]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [29]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

# lec9

In [30]:
import numpy as np

In [31]:
arr = np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[8]

8

In [34]:
arr[1:5]

array([1, 2, 3, 4])

In [35]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[0:5] = 100

In [37]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
arr = np.arange(0,11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
slice_arr = arr[0:6]

In [41]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [42]:
slice_arr[:] = 99

In [43]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
arr_copy = arr.copy()

In [45]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [46]:
arr_copy[:] = 50

In [47]:
arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [48]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [51]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2d[1]

array([20, 25, 30])

In [53]:
arr_2d[1][0]

20

In [54]:
arr_2d[1,0]

20

In [55]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [57]:
arr_2d[2]

array([35, 40, 45])

In [58]:
arr_2d[2,:]

array([35, 40, 45])

In [59]:
arr2d = np.zeros((10,10))

In [60]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
arr_length = arr2d.shape[1]

In [66]:
for i in range(arr_length):
  arr2d[i] = i

In [67]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [68]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [69]:
arr2d[[6,4,2,8]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])